/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr2_swing;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Nacho
 */
public class VentanaP extends javax.swing.JFrame {
    
    public void paint(Graphics g){
        super.paint(g);
        //CODIGO
        Point p = null;
        g.fillOval(p.x-5, p.y-5, 5, 5);
        //g.drawOval(p.x-5, 1, 5, 5);
    }

    /**
     * Creates new form ventanaP
     */
    public VentanaP() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        BotonP = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(formListener);
        getContentPane().setLayout(new java.awt.FlowLayout());

        BotonP.setText("Boton");
        BotonP.addMouseMotionListener(formListener);
        BotonP.addMouseListener(formListener);
        getContentPane().add(BotonP);

        Boton2.setText("Boton2");
        Boton2.addMouseListener(formListener);
        Boton2.addActionListener(formListener);
        getContentPane().add(Boton2);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == Boton2) {
                VentanaP.this.Boton2ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == BotonP) {
                VentanaP.this.BotonPMouseClicked(evt);
            }
            else if (evt.getSource() == VentanaP.this) {
                VentanaP.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == Boton2) {
                VentanaP.this.Boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == BotonP) {
                VentanaP.this.BotonPMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == BotonP) {
                VentanaP.this.BotonPMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaP.this) {
                VentanaP.this.formMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaP.this) {
                VentanaP.this.formMouseReleased(evt);
            }
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == BotonP) {
                VentanaP.this.BotonPMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMouseClicked
        // TODO add your handling code here:
        this.BotonP.setBackground(Color.red);
    }//GEN-LAST:event_BotonPMouseClicked

    private void BotonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMouseEntered
        // TODO add your handling code here:
        this.BotonP.setBackground(Color.blue);
    }//GEN-LAST:event_BotonPMouseEntered

    private void BotonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMouseExited
        // TODO add your handling code here:
        this.BotonP.setBackground(Color.green);
    }//GEN-LAST:event_BotonPMouseExited

    private void BotonPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMouseDragged
        //this.BotonP.setBackground(Color.darkGray);
        
    }//GEN-LAST:event_BotonPMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here: //DIBUJAR PUNTOS
        p=evt.getPoint();
        thv.repaint();
    }//GEN-LAST:event_formMouseClicked

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        this.Boton2.setBackground(Color.lightGray);
    }//GEN-LAST:event_Boton2MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:    //
        //Graphics g = this.getGraphics();
        //g.drawOval(evt.getX(), evt.getY(), 3, 3);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton2;
    private javax.swing.JButton BotonP;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
